language: Java
jdk:
  - oraclejdk8
branches:
  only:
    - master
script:
  - wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
  - java -jar BuildTools.jar --rev latest
